### ISSUE TITLE
Encoding missing for windows

### ISSUE THREAD

**Issue by AnEmortalKid** [mrc0mmand/SteamParty#1]
When I try to run steamparty, I get an error based on charmap:

```
$ python SteamParty.py 76561198073584574 76561197989468030
2018-05-13 17:27:57,417 [SteamParty/__init__] WARNING: No local cache found, fetching data may take some time
2018-05-13 17:27:57,417 [SteamParty/get_games] INFO: http://steamcommunity.com/profiles/76561198073584574/games/?tab=all
2018-05-13 17:27:57,417 [SteamParty/get_games] INFO: Fetching games for user 76561198073584574
2018-05-13 17:27:58,255 [SteamParty/get_games] ERROR: Failed to parse response data
Traceback (most recent call last):
  File "SteamParty.py", line 209, in <module>
    games = grabber.get_games(user)
  File "SteamParty.py", line 155, in get_games
    print(data)
  File "C:\Users\JMonterrubio\AppData\Local\Programs\Python\Python36-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 12621-12629: character maps to <undefined>
```

Python version:

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
```

**Comment by mrc0mmand** [comment]
Hi and sorry for a late response.

That `charmap` error is actually caused by exception, which is dumping the entire HTML page on stdout. Nevertheless, the main issue here is that both accounts you're trying to compare have hidden game list (I guess that's caused by your profile privacy settings). Without game data the script can't work properly. The error message should definitely mention this, so I'll update it.

Thanks!
